services:
  ludocode-backend:
    container_name: ludocode-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORTS}
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      GCS_ENABLED: ${GCS_ENABLED}
      PISTON_ENABLED: ${PISTON_ENABLED}
      DEMO_ENABLED: ${DEMO_ENABLED}
      GEMINI_MODEL: ${GEMINI_MODEL}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      COOKIE_DOMAIN: ${COOKIE_DOMAIN}
      COOKIE_SAME_SITE: ${COOKIE_SAME_SITE}
      COOKIE_SECURE: ${COOKIE_SECURE}
      FRONTEND_ORIGINS: ${FRONTEND_ORIGINS}
      LIQUIBASE_CONTEXT: ${LIQUIBASE_CONTEXT}
      FIREBASE_SERVICE_ACCOUNT_PATH: ${FIREBASE_SERVICE_ACCOUNT_PATH}
      STORAGE_MODE: ${STORAGE_MODE}
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GCS_BUCKET_NAME: ${GCS_BUCKET_NAME}
      GCS_PROJECT_ID: ${GCS_PROJECT_ID}
      PISTON_BASE: ${PISTON_BASE}
      DEMO_TOKEN: ${DEMO_TOKEN}
      DEMO_USER_ID: ${DEMO_USER_ID}

    volumes:
      - ./local-storage:/data/local-bucket