services:
  ludocode-backend:
    container_name: ludocode-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVER_PORTS}
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./local-storage:/data/local-bucket