spring.application.name=ludocode-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/ludocode
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
logging.level.org.springframework.security: DEBUG

# Google OAuth2
jwt.secret=096c24a818694d2758390584c1066fd2
google.client-id=803670292191-ril5j113o5t85sbaduefgk3jn55423b1.apps.googleusercontent.com
google.client-secret=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
google.redirect-uri=postmessage
# Cookie Configurations
auth.cookie.name=jwt
auth.cookie.path=/
auth.cookie.domain=
auth.cookie.same-site=Lax
auth.cookie.secure=false
auth.cookie.max-age-seconds=86400


user.service.base-url=http://localhost:8080
catalog.service.base-url=http://localhost:8080
course-progress.service.base-url=http://localhost:8080