spring:
  application:
    name: ludocode-backend

  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
  cache:
    type: ${CACHE_TYPE:none}
  data:
    redis:
      enabled: ${REDIS_ENABLED:false}
      repositories:
        enabled: false
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: ${LIQUIBASE_CONTEXT:dev}
    #profiles: admin, dev, devadmin, prod, test, devtestadmin
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:devadmin}

management:
  health:
    redis:
      enabled: ${REDIS_ENABLED:false}

yaml:
  schemas:
    curriculum: ${CURRICULUM_SCHEMA_SERVER:http://localhost:8080}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}
    com.ludocode.ludocodebackend.commons.configuration.com.ludocode.ludocodebackend.commons.configuration.web.CorsLoggingFilter: ${CORS_LOGGING_LEVEL:WARN}

payments:
  enabled: ${PAYMENTS_ENABLED:false}

stripe:
  enabled: ${STRIPE_ENABLED:false}
  mode: ${STRIPE_MODE:FREE_ONLY}
  secret-key: ${STRIPE_SECRET_KEY}
  webhook-secret: ${STRIPE_WEBHOOK_SECRET}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui
    enabled: true

firebase:
  enabled: ${FIREBASE_ENABLED:false}
  service:
    json: ${FIREBASE_SERVICE_ACCOUNT_JSON}

ai:
  enabled: ${AI_ENABLED:false}
  api:
    key: ${GEMINI_API_KEY}
  model: ${GEMINI_MODEL:gemini-2.5-flash-lite}

jwt:
  secret: ${JWT_SECRET}

cors:
  origins: ${FRONTEND_ORIGINS:http://localhost:5173}

avatar:
  version: v1
  count: 10

app:
  jobs:
    monthly-credit-reset:
      cron: ${MONTHLY_CREDIT_RESET_CRON:0 0 0 1 * *}
      zone: ${MONTHLY_CREDIT_RESET_ZONE:UTC}
    project-cleanup:
      cron: ${PROJECT_CLEANUP_CRON:0 */5 * * * *}
      zone: ${PROJECT_CLEANUP_ZONE:UTC}

  frontend-url: ${FRONTEND_URL}
  gcs-host:

# mode: local, s3, gcs
storage:
  mode: ${STORAGE_MODE:local}

  gcs:
    bucket: ${GCS_BUCKET_NAME}
    project:
      id: ${GCS_PROJECT_ID}
    credentials-json: ${GCS_CREDENTIALS_JSON:}
  s3:
    region: ${AWS_REGION:eu-central-1}
    bucket: ${S3_BUCKET_NAME}
    endpoint: ${S3_ENDPOINT}
  local:
    bucket-name: ${LOCAL_BUCKET_NAME:/data/local-bucket}

piston:
  enabled: ${PISTON_ENABLED:false}
  public: https://emkc.org/api/v2/piston
  base: ${PISTON_BASE}

demo:
  user-id: ${DEMO_USER_ID:598ccbea-4957-4569-81cb-ea901b62c329}

auth:
  cookie:
    name: jwt
    path: /
    domain: ${COOKIE_DOMAIN:localhost}
    same-site: ${COOKIE_SAME_SITE:Lax}
    secure: ${COOKIE_SECURE:false}
    max-age-seconds: 86400